CREATE TABLE MODULOS(
    ID_MODULO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_MODULO)
);

CREATE TABLE TIPO_EMPLEADO(
    ID_TIPO_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_TIPO_EMPLEADO)
);

CREATE TABLE DEPARTAMENTOS(
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_DEPARTAMENTO)
);

CREATE TABLE PROYECTOS(
    ID_PROYECTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_PLAZO DATETIME,
    PRIMARY KEY(ID_PROYECTO)
);

CREATE TABLE ROLES(
    ID_ROL INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PRIMARY KEY(ID_ROL),
);

CREATE TABLE ROL_MODULOS(
    ID_ROL_MODULO INT NOT NULL AUTO_INCREMENT,
    ID_ROL INT NOT NULL,
    ID_MODULO INT NOT NULL,
    PRIMARY KEY(ID_ROL_MODULO),
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL),
    FOREIGN KEY(ID_MODULO) REFERENCES MODULOS(ID_MODULO)
);

CREATE TABLE EMPLEADOS(
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    FECHA_CONTRATO DATETIME NOT NULL,
    SALARIO INT NOT NULL,
    CORREO VARCHAR(255),
    TELEFONO VARCHAR(12) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    RUT VARCHAR(9) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    ID_TIPO_EMPLEADO INT NOT NULL,
    PRIMARY KEY(ID_EMPLEADO),
    FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
    FOREIGN KEY(ID_TIPO_EMPLEADO) REFERENCES TIPO_EMPLEADO(ID_TIPO_EMPLEADO)
);

CREATE TABLE INFORMES(
    ID_INFORME INT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    FECHA DATETIME NOT NULL,
    REPORTE VARCHAR(255),
    PRIMARY KEY(ID_INFORME),
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE ASIGNACIONES(
    ID_ASIGNACION INT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    PRIMARY KEY(ID_ASIGNACION),
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);

CREATE TABLE EMPLEADO_ROL(
    ID_EMPLEADO_ROL INT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_ROL INT NOT NULL,
    PRIMARY KEY(ID_EMPLEADO_ROL),
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE PROYECTO_EMPLEADO(
    ID_PROYECTO_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_PROYECTO INT NOT NULL,
    PRIMARY KEY(ID_PROYECTO_EMPLEADO),
    FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTOS(ID_PROYECTO)
);

CREATE TABLE REGISTRO_TIEMPO(
    ID_REGISTRO_TIEMPO INT NOT NULL AUTO_INCREMENT,
    FECHA DATETIME NOT NULL,
    CANTIDAD_HORAS INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ID_PROYECTO_EMPLEADO INT NOT NULL,
    PRIMARY KEY(ID_REGISTRO_TIEMPO),
    FOREIGN KEY(ID_PROYECTO_EMPLEADO) REFERENCES PROYECTO_EMPLEADO(ID_PROYECTO_EMPLEADO)
);